### ISSUE TITLE
Stereochemistry (tetrahedral, double-bond) options?

### ISSUE THREAD

**Issue by someonetookmyname** [chembl/FPSim2#75]
Hi,

Thank you for this software!

As presented in the documentation, we're using Morgan fingerprints for similarity searches and RDKPatternFingerprint's for substructure searches.  When calculated as in the documentation examples, neither seems to consider stereochemistry (tetrahedral or double-bond).

Are there options for either/both so that stereochemistry is considered?

Thank you for any guidance.

Best regards,

Andrew

**Comment by eloyfelix** [comment]
Hi Andrew,

FPSim2 is using this RDKit function to generate Morgan fingerprints: 

http://rdkit.org/docs/source/rdkit.Chem.rdMolDescriptors.html#rdkit.Chem.rdMolDescriptors.GetMorganFingerprintAsBitVect

which means that you could use the `useChirality` flag which is set as False by default when creating the fingerprints file
{'radius': 2, 'nBits': 2048, 'useChirality': False}

**Comment by someonetookmyname** [comment]
Thank you for the response.

Is it ok to use Morgan fingerprints for substructure searches? https://chembl.github.io/FPSim2/source/user_guide/subs.html recommends to use RDKPatternFingerprints, but I cannot find a similar "useChirality" option for that fingerprint type?

Thank you.

**Comment by eloyfelix** [comment]
Be aware that the substructure function in FPSim2 does not run a full substructure search. It is mentioned in the documentation and you coud bet a getter idea of what you'll get from it in Greg's blogpost: http://rdkit.blogspot.com/2013/11/fingerprint-based-substructure.html TL;DR section.

There is no such parameter in RDKit for the RDKPatternFingerprints. It is recommended by FPSim2 because is the best option in RDKit :) I didn't experimented with Morgan but I'm afraid they can have much worse accuracy than the specificaly designed fingerprints.
